# Principal Component Analysis

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [2]:
df1 = pd.read_csv('student-mat.csv', delimiter= ";")
df2 = pd.read_csv('student-por.csv', delimiter = ';')

df1.shape
df2.shape


(395, 33)

(649, 33)

In [3]:
df = pd.merge(df1, df2, how='outer')
df.head()
df.shape

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other ...   
3     GP   F   15       U     GT3       T     4     2   health  services ...   
4     GP   F   16       U     GT3       T     3     3    other     other ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

(1044, 33)

In [4]:
df.isnull().any()

school        False
sex           False
age           False
address       False
famsize       False
Pstatus       False
Medu          False
Fedu          False
Mjob          False
Fjob          False
reason        False
guardian      False
traveltime    False
studytime     False
failures      False
schoolsup     False
famsup        False
paid          False
activities    False
nursery       False
higher        False
internet      False
romantic      False
famrel        False
freetime      False
goout         False
Dalc          False
Walc          False
health        False
absences      False
G1            False
G2            False
G3            False
dtype: bool

In [7]:
cols = df.select_dtypes(include=['object']).columns
cols

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

In [8]:
for col in cols:
    df[col]= pd.Categorical(df[col]).codes


In [9]:
df.head()

school  sex  age  address  famsize  Pstatus  Medu  Fedu  Mjob  Fjob ...  \
0       0    0   18        1        0        0     4     4     0     4 ...   
1       0    0   17        1        0        1     1     1     0     2 ...   
2       0    0   15        1        1        1     1     1     0     2 ...   
3       0    0   15        1        0        1     4     2     1     3 ...   
4       0    0   16        1        0        1     3     3     2     2 ...   

   famrel  freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
0       4         3      4     1     1       3         6   5   6   6  
1       5         3      3     1     1       3         4   5   5   6  
2       4         3      2     2     3       3        10   7   8  10  
3       3         2      2     1     1       5         2  15  14  15  
4       4         3      2     1     2       5         4   6  10  10  

[5 rows x 33 columns]

In [10]:
df.select_dtypes(include=['object']).columns

Index([], dtype='object')

In [11]:
df[['G1', 'G2', 'G3']].corr()

G1        G2        G3
G1  1.000000  0.858739  0.809142
G2  0.858739  1.000000  0.910743
G3  0.809142  0.910743  1.000000

In [14]:
df.drop(['G1', 'G2'], axis=1, inplace=True)
df.shape

(1044, 31)

In [15]:
x=df.iloc[:, :-1].values
y=df.iloc[:, -1].values

In [22]:
# PCA 
from sklearn.decomposition import PCA
pca = PCA(n_components = len(df.columns)-1)
pca.fit(x)

variance_ratio = pca.explained_variance_ratio_
np.round(variance_ratio,2)

cumilative_ratio = np.cumsum(variance_ratio)

np.round(cumilative_ratio, 2)

PCA(copy=True, iterated_power='auto', n_components=30, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

array([ 0.66,  0.05,  0.05,  0.04,  0.03,  0.02,  0.02,  0.02,  0.01,
        0.01,  0.01,  0.01,  0.01,  0.01,  0.01,  0.01,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
        0.  ,  0.  ,  0.  ])

array([ 0.66,  0.71,  0.76,  0.8 ,  0.82,  0.84,  0.87,  0.88,  0.9 ,
        0.91,  0.92,  0.93,  0.94,  0.95,  0.95,  0.96,  0.97,  0.97,
        0.97,  0.98,  0.98,  0.98,  0.99,  0.99,  0.99,  0.99,  1.  ,
        1.  ,  1.  ,  1.  ])

In [23]:
#From above we can conisder 10 components 
pca = PCA(10)
pca.fit(x)
x_pca = pca.fit_transform(x)


PCA(copy=True, iterated_power='auto', n_components=10, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [24]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(x_pca, y)

from sklearn.model_selection import cross_val_score
cv_score = cross_val_score(lr, x_pca, y, cv=10)
cv_score
cv_score.mean()

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\model_selection\_split.py:597: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


array([ 0.15652174,  0.13513514,  0.12844037,  0.23076923,  0.13461538,
        0.19417476,  0.15533981,  0.15      ,  0.20408163,  0.19587629])

0.16849543410423135