In [1]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

In [18]:
df = pd.read_csv('abalone.csv')
df.head()

Sex  Length    Diameter  Height   Whole weight     Shucked weight  \
0   M     0.455     0.365    0.095           0.5140          0.2245   
1   M     0.350     0.265    0.090           0.2255          0.0995   
2   F     0.530     0.420    0.135           0.6770          0.2565   
3   M     0.440     0.365    0.125           0.5160          0.2155   
4   I     0.330     0.255    0.080           0.2050          0.0895   

   Viscera weight   Shell weight     Rings  
0           0.1010            0.150     15  
1           0.0485            0.070      7  
2           0.1415            0.210      9  
3           0.1140            0.155     10  
4           0.0395            0.055      7

In [19]:
df.isnull().any()

Sex                False
Length             False
Diameter           False
Height             False
Whole weight       False
Shucked weight     False
Viscera weight     False
Shell weight       False
Rings              False
dtype: bool

In [22]:
# converting sex into 0 and 1 
df['Sex'].value_counts()

M    1528
I    1342
F    1307
Name: Sex, dtype: int64

In [23]:
df['Sex'] = pd.Categorical(df['Sex']).codes
df['Sex'].value_counts()

2    1528
1    1342
0    1307
Name: Sex, dtype: int64

In [24]:
x=df.drop('Sex', axis=1).values
y = df['Sex'].values
x[:3]

array([[  0.455 ,   0.365 ,   0.095 ,   0.514 ,   0.2245,   0.101 ,
          0.15  ,  15.    ],
       [  0.35  ,   0.265 ,   0.09  ,   0.2255,   0.0995,   0.0485,
          0.07  ,   7.    ],
       [  0.53  ,   0.42  ,   0.135 ,   0.677 ,   0.2565,   0.1415,
          0.21  ,   9.    ]])

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [26]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x,y, test_size=0.33, random_state=0)

In [27]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=1e42)
lr.fit(xtr, ytr)


LogisticRegression(C=1e+42, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [28]:
ypr = lr.predict(xts)

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cm = confusion_matrix(yts, ypr)
ac = accuracy_score(yts, ypr)
clr =  classification_report(yts, ypr)
cm
ac
print(clr)

array([[148,  79, 202],
       [ 31, 382,  46],
       [139, 121, 231]], dtype=int64)

0.551849166062364

             precision    recall  f1-score   support

          0       0.47      0.34      0.40       429
          1       0.66      0.83      0.73       459
          2       0.48      0.47      0.48       491

avg / total       0.53      0.55      0.54      1379



In [33]:
# K Fold Cross Validation 
from sklearn.model_selection import cross_val_score

lgr = LogisticRegression(C=1e42)

cv = cross_val_score(lgr, x,y, cv=10, scoring='accuracy')
cv
cv.mean()

array([ 0.47494033,  0.51551313,  0.57177033,  0.57894737,  0.53827751,
        0.52631579,  0.62679426,  0.53477218,  0.58413462,  0.56490385])

0.55163693675710779

In [34]:
# Applying gird Search for C parameter 

from sklearn.model_selection import GridSearchCV

clf = LogisticRegression()
params = {'C':[0.01, 0.1, 1, 10, 100]}

grid = GridSearchCV(clf, params)
grid_model = grid.fit(xtr, ytr)

In [35]:
grid_model.best_params_

{'C': 100}

In [36]:
grid_model.best_score_

0.54681915654038604