In [3]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

df = pd.read_csv('Social_Network_Ads.csv')
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [4]:
df = df.iloc[:, 1:] # User ID is not required for analysis 
df.head(3)

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0

In [5]:
df['Gender'].value_counts()

Female    204
Male      196
Name: Gender, dtype: int64

In [6]:
df['Gender']=df['Gender'].apply(lambda sex:0 if sex=='Female' else 1)
df.head(3)

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0

In [8]:
# x,y declaration
x= df.iloc[:, :3].values
y = df.iloc[:, 3].values
x[:3]
y[:3]

array([[    1,    19, 19000],
       [    1,    35, 20000],
       [    0,    26, 43000]], dtype=int64)

array([0, 0, 0], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x, y , test_size= .3, random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

xtr_sc = sc.fit_transform(xtr)
xts_sc = sc.transform(xts)

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(xtr_sc, ytr)

ypr = clf.predict(xts_sc)

GaussianNB(priors=None)

In [21]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm = confusion_matrix(yts, ypr)
ac = accuracy_score(yts, ypr)
clr = classification_report(yts, ypr)

In [23]:
cm
ac
print(clr)

array([[76,  3],
       [ 8, 33]], dtype=int64)

0.90833333333333333

             precision    recall  f1-score   support

          0       0.90      0.96      0.93        79
          1       0.92      0.80      0.86        41

avg / total       0.91      0.91      0.91       120



In [26]:
# Applying cross validation 
from sklearn.model_selection import cross_val_score
scores = cross_val_score(clf, xtr_sc, ytr , cv=10, scoring='accuracy')
scores

array([ 0.86206897,  0.79310345,  0.89285714,  0.89285714,  0.71428571,
        0.78571429,  0.92857143,  0.96428571,  0.96296296,  1.        ])

In [27]:
scores.mean()

0.87967068053274955