In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('Wine.csv')
df.head(3)

Alcohol  Malic_Acid   Ash  Ash_Alcanity  Magnesium  Total_Phenols  \
0    14.23        1.71  2.43          15.6        127           2.80   
1    13.20        1.78  2.14          11.2        100           2.65   
2    13.16        2.36  2.67          18.6        101           2.80   

   Flavanoids  Nonflavanoid_Phenols  Proanthocyanins  Color_Intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   

   OD280  Proline  Customer_Segment  
0   3.92     1065                 1  
1   3.40     1050                 1  
2   3.17     1185                 1

In [3]:
df['Customer_Segment'].value_counts()

2    71
1    59
3    48
Name: Customer_Segment, dtype: int64

In [4]:
df.shape

(178, 14)

In [5]:
x = df.iloc[:, :13].values
y = df.iloc[:, 13].values

In [8]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x,y, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xtr = sc.fit_transform(xtr)
xts = sc.transform(xts)

In [21]:
# Applying LDA 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=3)
xtr = lda.fit_transform(xtr, ytr)
xts = lda.transform(xts)
print(lda.explained_variance_ratio_)


[ 0.73846314  0.26153686]


In [18]:
# Fitting Logistic Regression for training set 
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=1e42)
lr.fit(xtr, ytr)

ypr = lr.predict(xts)


[ 0.73846314  0.26153686]


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, classification_report
cm = confusion_matrix(yts, ypr)
acc = accuracy_score(yts, ypr)
cls = classification_report(yts, ypr)
#roc = roc_auc_score(yts, ypr)

print(cm, acc, cls)


[[19  0  0]
 [ 0 22  0]
 [ 0  0 13]] 1.0              precision    recall  f1-score   support

          1       1.00      1.00      1.00        19
          2       1.00      1.00      1.00        22
          3       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        54



In [16]:
from sklearn.model_selection import cross_val_score
cv_score = cross_val_score(lr, xtr, ytr, cv=10, scoring='accuracy')
cv_score

array([ 1.        ,  1.        ,  1.        ,  1.        ,  0.92307692,
        1.        ,  1.        ,  1.        ,  1.        ,  1.        ])

In [17]:
cv_score.mean()

0.99230769230769234