In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv('data.csv')
df.head(3)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38           122.8     1001.0   
1    842517         M        20.57         17.77           132.9     1326.0   
2  84300903         M        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

      ...       texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0     ...               17.33            184.6      2019.0            0.1622   
1     ...               23.41            158.8      1956.0            0.1238   
2     ...               25.53            152.5      1709.0            0.1444   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  

[3 rows x 33 columns]

In [6]:
del df['id']
del df['Unnamed: 32']
df['diagnosis'] = df['diagnosis'].apply(lambda x:0 if x=='M' else 1)
df.head(3)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0        17.99         10.38           122.8     1001.0   
1          0        20.57         17.77           132.9     1326.0   
2          0        19.69         21.25           130.0     1203.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   

   symmetry_mean           ...             radius_worst  texture_worst  \
0         0.2419           ...                    25.38          17.33   
1         0.1812           ...                    24.99          23.41   
2         0.2069           ...                    23.57          25.53   

   perimeter_worst  area_worst  smoothness_worst  compactness_worst  \
0            184.6      2019.0            0.1622             0.6656   
1            158.8      1956.0            0.1238             0.1866   
2            152.5      1709.0            0.1444             0.4245   

   concavity_worst  concave points_worst  symmetry_worst  \
0           0.7119                0.2654          0.4601   
1           0.2416                0.1860          0.2750   
2           0.4504                0.2430          0.3613   

   fractal_dimension_worst  
0                  0.11890  
1                  0.08902  
2                  0.08758  

[3 rows x 31 columns]

In [7]:
x = df.drop('diagnosis', axis=1).values
y = df['diagnosis'].values

In [8]:
from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x,y,test_size=0.3, random_state=0)


In [11]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components=3)
xtr = lda.fit_transform(xtr, ytr)
xts = lda.transform(xts)
lda.explained_variance_ratio_

array([ 1.])

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=1e42)
lr.fit(xtr, ytr)

ypr = lr.predict(xts)


In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, classification_report
cm = confusion_matrix(yts, ypr)
acc = accuracy_score(yts, ypr)
cls = classification_report(yts, ypr)
roc = roc_auc_score(yts, ypr)

print(cm, '\n', acc,'\n', cls,'\n', roc)

[[ 59   4]
 [  2 106]] 
 0.964912280702 
              precision    recall  f1-score   support

          0       0.97      0.94      0.95        63
          1       0.96      0.98      0.97       108

avg / total       0.96      0.96      0.96       171
 
 0.958994708995


In [16]:
from sklearn.model_selection import cross_val_score
cv_score = cross_val_score(lr, xtr, ytr, cv=10, scoring='accuracy')
cv_score

array([ 0.975,  1.   ,  0.95 ,  0.975,  0.975,  0.975,  1.   ,  1.   ,
        1.   ,  1.   ])

In [17]:
cv_score.mean()

0.98499999999999999