In [10]:
import pandas as pd, numpy as np
df = pd.read_csv('Social_Network_Ads.csv')
df.head(3)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0

In [11]:
df= df.iloc[:, 1:]
df.head(3)

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0

In [12]:
df['Gender']=np.where(df['Gender']=='Male', 1, 0)
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [16]:
x= df.iloc[:, :3].values
y = df.iloc[:, 3].values

from sklearn.model_selection import train_test_split
xtr, xts, ytr, yts = train_test_split(x, y , test_size= .3, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

xtr = sc.fit_transform(xtr)
xts = sc.transform(xts)


C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\utils\validation.py:444: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [18]:
from sklearn.svm import SVC
sv1 = SVC(kernel='linear', random_state=0)
sv1.fit(xtr, ytr)

ypr1 = sv1.predict(xts)


In [20]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
cm = confusion_matrix(yts, ypr1)
acc = accuracy_score(yts, ypr1)
cls = classification_report(yts, ypr1)

print(cm)
print(acc)
print(cls)

[[76  3]
 [13 28]]
0.866666666667
             precision    recall  f1-score   support

          0       0.85      0.96      0.90        79
          1       0.90      0.68      0.78        41

avg / total       0.87      0.87      0.86       120



In [23]:
from sklearn.svm import SVC
sv2 = SVC(kernel='rbf', random_state=0)
sv2.fit(xtr, ytr)

ypr2 = sv2.predict(xts)

cm = confusion_matrix(yts, ypr2)
acc = accuracy_score(yts, ypr2)
cls = classification_report(yts, ypr2)

print(cm)
print(acc)
print(cls)


[[74  5]
 [ 4 37]]
0.925
             precision    recall  f1-score   support

          0       0.95      0.94      0.94        79
          1       0.88      0.90      0.89        41

avg / total       0.93      0.93      0.93       120



In [26]:
from sklearn.model_selection import cross_val_score
cv_score_lin = cross_val_score(sv1, xtr, ytr, cv=10, scoring='accuracy')
cv_score_lin

array([ 0.75862069,  0.82758621,  0.78571429,  0.85714286,  0.67857143,
        0.67857143,  0.92857143,  0.92857143,  0.88888889,  0.88888889])

In [27]:
cv_score_lin.mean()

0.82211275314723609

In [28]:
cv_score_rbf = cross_val_score(sv1, xtr, ytr, cv=10, scoring='accuracy')
cv_score_rbf

array([ 0.75862069,  0.82758621,  0.78571429,  0.85714286,  0.67857143,
        0.67857143,  0.92857143,  0.92857143,  0.88888889,  0.88888889])

In [29]:
cv_score_rbf.mean()

0.82211275314723609